name: Auto Green

on:
  schedule:
    - cron: '0 17 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Modify file
        run: |
          touch log.txt
          echo "Update $(date) $(uuidgen)" >> log.txt

      - name: Commit changes
        run: |
          git config --global user.name "JiaShuqi08"
          git config --global user.email "jia1shu2qi3@163.com"

          git add log.txt

          git commit -m "Auto update $(date +'%Y-%m-%d %H:%M:%S')" || exit 0

      - name: Push changes
        run: |
          git push
