name: Auto Green

on:
  schedule:
    # 每天北京时间凌晨1点执行
    - cron: '0 17 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update log file
        run: |
          echo "Update time: $(date)" >> log.txt

      - name: Commit and push
        run: |
          git config user.name "JiaShuqi08"
          git config user.email "jia1shu2qi3@163.com"

          git add .

          git commit -m "daily update $(date)" || echo "No changes"

          git push
